version: "3.1"

services:
  db:
    build:
      context: ./v2server
      dockerfile: Dockerfile.database
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./v2server/database/mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    links:
      - db
  server:
    env_file:
      - ./v2server/.env
    build:
      context: ./v2server
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - 49200:49200
    volumes:
      - ./v2server:/v2server
    entrypoint: yarn dev
    links:
      - db
    environment:
      - HOST=server
  client:
    build:
      context: ./v2client
      dockerfile: Dockerfile.dev
    image: msmf/client
    restart: always
    volumes:
      - ./v2client:/msmf/v2client
    ports:
      - 3000:3000
    entrypoint: yarn dev
    links:
      - server
