version: "3.1"

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "abc@123"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - db
  client_prod:
    build:
      context: ./v2client
      dockerfile: Dockerfile.prod
    image: msmf/client
    restart: always
    ports:
      - 3000:3000
    entrypoint: yarn dev
